steps:
- name: node
  id: "npm ci"
  entrypoint: npm
  args: ['ci']
- name: node
  id: "npm run lint"
  entrypoint: npm
  args: ['run', 'lint']
- name: node
  id: "npm run build:package"
  entrypoint: npm
  args: ['run', 'build:package']
- name: node
  id: "npm run test:ci"
  entrypoint: npm
  args: ['run', 'test:ci']
- name: node
  id: "npm run test:e2e:ci"
  entrypoint: npm
  args: ['run', 'test:e2e:ci']
- name: node
  id: "npm run semantic-release -- -d false --no-ci"
  entrypoint: npm
  env:
    - 'NPM_TOKEN=$_NPM_TOKEN'
    - 'GH_TOKEN=$_GH_TOKEN'
  args: ['run', 'semantic-release', '--', '-d', 'false', '--no-ci']
- name: node
  id: "npm run docs:deploy"
  entrypoint: npm
  args: ['run', 'docs:deploy']
